# Generated by Django 4.2.4 on 2023-09-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camisas_app', '0002_detalhes_rename_expecificacoes_camisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhes',
            name='camisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_camisa', to='camisas_app.camisa'),
        ),
    ]
